SELECT DISTINCT
    COUNTRY,
    REGEXP_REPLACE(COUNTRY, '[A-Za-z ]', '') AS SPECIAL_CHARS_FOUND
FROM {{ ref('lcbo_products_source') }}
WHERE COUNTRY IS NOT NULL
  AND COUNTRY != REGEXP_REPLACE(COUNTRY, '[^A-Za-z ]', '')
ORDER BY COUNTRY