models:
  - name: wine_reviews_source
    columns:
      - name: product_name
        data_tests:
          - not_null
      - name: points
        data_tests:
          - not_null
      - name: winery
        data_tests:
          - not_null
      - name: country
        data_tests:
          - not_null
      - name: variety
        data_tests:
          - not_null
      - name: region
        data_tests:
          - not_null
      - name: review_description
        data_tests:
          - not_null
  - name: lcbo_products_source
    columns:
      - name: product_id
        data_tests:
           - not_null
           - unique
      - name: abv
        data_tests:
          - not_null
      - name: product_name
        data_tests:
          - not_null
          - unique
      - name: class
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['wine','spirits','beers']
      - name: price
        data_tests:
          - not_null
      - name: volume
        data_tests:
          - not_null
      - name: country
        data_tests:
          - not_null
      - name: producer
        data_tests:
          - not_null
      - name: lcbo_products_spl_char